### ISSUE TITLE
Download link typo

### ISSUE THREAD

**Issue by StevenSong** [rajewsky-lab/openst#22]
## Issue/Improvement Description
Download link for adult mouse hippocampus h5ad file is broken, seems like it's just missing `_mouse` in the url
https://github.com/rajewsky-lab/openst/blob/4853c99566f796e87282b4bafd827dca838ce239/docs/examples/datasets.md?plain=1#L9

## Context
New dataset links

## Proposed Changes
http://bimsbstatic.mdc-berlin.de/rajewsky/openst-public-data/adult_mouse_hippocampus.h5ad.tar.gz

## Additional Information
Thanks for sharing the dataset, been looking forward to playing around with it!

**Comment by danilexn** [comment]
Thanks so much for reporting! I fix it now :)
