### ISSUE TITLE
Docker image not accessible 

### ISSUE THREAD

**Issue by taranehstrunk** [rajewsky-lab/openst#26]
We are trying to pull your docker image but I think it's not available publicly. 

## I am executing
```sh
docker pull rajewski/openst
```
I am logged in with my docker account. I also can't find the image when I search for it online. 

## But receive the following error:
Using default tag: latest
```Error response from daemon: pull access denied for rajewsky/openst, repository does not exist or may require 'docker login': denied: requested access to the resource is denied```

I additionally tried installing the package with pip and from the github directly but cannot identify the right versions for all the required packages. I think there might be some compatibility issues. 

Thanks for your help. 

## Environment info
- OS:  macOS 14.2.1 (23C71) 
- Docker version: 25.0.3
- Python version: 3.11.8

**Comment by danilexn** [comment]
Hi! You're right, the docker image was not available - apologies!

We will make it available today, it will be possible to pull and run it using the commands in the tutorial. I will let you know, and then will close the issue

**Comment by danilexn** [comment]
The docker image is now available. It supports `openst` via terminal, and GUI tools via browser - please see updated docs:

https://rajewsky-lab.github.io/openst/latest/computational/getting_started/#with-docker

:hugs:
