### ISSUE TITLE
Question about flowcell division

### ISSUE THREAD

**Issue by JiaGuangshuai** [rajewsky-lab/openst#50]
Hi,

I'm curious about why it's necessary to divide the flowcell into strips and smaller blocks. 

Could you use the entire, or half (or 1/4 ....) of the flowcell instead? Is the division due to the flowcell being composed of smaller grids? Are there barcode overlaps between different lanes of the flowcell, preventing the use of larger areas? If use a larger area, would there be blank regions (gaps) without barcodes in between? 

Thank you!

**Comment by danilexn** [comment]
Hi!

In theory, you can use the full flow cell – there is very little overlap between barcodes (>80% of them are unique).

Using the NovaSeq 6000 S4, there is too much "empty" space between lanes, so process very large pieces of tissue might become infeasible. Also, the sequencing investment for such a sample might be too high. 

The maximum rather continuous area are the individual lanes. These are 7 x 89 mm each. You can flexibly decide how to cut the pieces per lane with the help of the 3D-printable cutting guide, and as shown in the video. Within the lanes, there are some regular gaps, but these are dramatically smaller than the gaps between lanes.

Best,
Daniel

**Comment by jefferyUstc** [comment]
Regarding the flow cell, I have a question. The tile is supposed to be 1mm by 1mm in size, and the resolution should be 0.6 µm. By my calculation, the spatial barcodes in the x and y axes should be approximately 1mm / 0.6 µm ≈ 1700.

However, after downloading the [example tile files](http://bimsbstatic.mdc-berlin.de/rajewsky/openst-public-data/adult_hippocampus_tiles.tar.xz) from the website, I found that the min and max x-coordinates are around 1000 and 32000, respectively, and the min and max y-coordinates are about 1000 and 37000.

I don't understand how there can be so many points within a single tile. Thank you for your time.

**Comment by danilexn** [comment]
This issue is closed in the chat, see:

>In reply to ￼ Hi openst team and friends, I have a question for flow cell structure. The tile is supposed to be 1mm by 1mm in size, and the resolution should be 0.6 µm. By my calculation, the spatial barcodes in the x and y axes should be approximately 1mm / 0.6 µm ≈ 1700. However, after downloading the example tile files from the openST website, I found that the min and max x-coordinates are around 1000 and 32000, respectively, and the min and max y-coordinates are about 1000 and 37000. I don't understand how there can be so many points within a single tile.

>
Hi ￼ , the size of tiles is roughly 1.1 mm by 1.3 mm, which explains why the max for the y-coordinates is higher. Also both x and y coordinates increase by a specific range (~16-17), so that you only have ~2,000 of them in a given dimension.
