### ISSUE TITLE
Download the H&E image

### ISSUE THREAD

**Issue by wsyyc** [rajewsky-lab/openst#58]
Hi openst team,
    I would like to know where I can download the H&E stained slides corresponding to all the data. I didn't see any related information on GEO.
Thank you!

**Comment by nukappa** [comment]
Hi @wsyyc, the HE images are included in the `h5ad` objects which you can download from GEO. Links [here](https://rajewsky-lab.github.io/openst/main/examples/getting_started/).

**Comment by wsyyc** [comment]
Thank you, is the H&E images saved in adata.uns['spatial']['tissue'] ?

**Comment by danilexn** [comment]
Hi! Yes, and masks generated with the `openst` pipeline are available in `adata.uns['spatial']['mask']`

**Comment by wsyyc** [comment]
Thanks for your response!
