### ISSUE TITLE
About the data release

### ISSUE THREAD

**Issue by musikisomorphie** [rajewsky-lab/openst#9]
Dear author,

I was wondering when the mouse/human tissue and ST data mentioned in the paper could be released.
Thank you very much.

**Comment by danilexn** [comment]
Hi! Thanks for your message! 

The data was uploaded to GEO:

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE251926

and will be released as soon as the paper is peer-reviewed and published.

**Comment by musikisomorphie** [comment]
Thank you for the response, best wishes for your submission!
